#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-zjsonpatch
Version  : 0.3.0
Release  : 3
URL      : https://github.com/fabric8io/zjsonpatch/archive/v0.3.0.tar.gz
Source0  : https://github.com/fabric8io/zjsonpatch/archive/v0.3.0.tar.gz
Source1  : https://repo1.maven.org/maven2/com/flipkart/zjsonpatch/zjsonpatch/0.4.4/zjsonpatch-0.4.4.jar
Source2  : https://repo1.maven.org/maven2/com/flipkart/zjsonpatch/zjsonpatch/0.4.4/zjsonpatch-0.4.4.pom
Source3  : https://repo1.maven.org/maven2/io/fabric8/zjsonpatch/0.3.0/zjsonpatch-0.3.0.jar
Source4  : https://repo1.maven.org/maven2/io/fabric8/zjsonpatch/0.3.0/zjsonpatch-0.3.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-zjsonpatch-data = %{version}-%{release}
Requires: mvn-zjsonpatch-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
# This is an implementation of  [RFC 6902 JSON Patch](http://tools.ietf.org/html/rfc6902) written in Java.

%package data
Summary: data components for the mvn-zjsonpatch package.
Group: Data

%description data
data components for the mvn-zjsonpatch package.


%package license
Summary: license components for the mvn-zjsonpatch package.
Group: Default

%description license
license components for the mvn-zjsonpatch package.


%prep
%setup -q -n zjsonpatch-0.3.0

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-zjsonpatch
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-zjsonpatch/LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/flipkart/zjsonpatch/zjsonpatch/0.4.4
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/flipkart/zjsonpatch/zjsonpatch/0.4.4/zjsonpatch-0.4.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/flipkart/zjsonpatch/zjsonpatch/0.4.4
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/flipkart/zjsonpatch/zjsonpatch/0.4.4/zjsonpatch-0.4.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/fabric8/zjsonpatch/0.3.0
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/io/fabric8/zjsonpatch/0.3.0/zjsonpatch-0.3.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/fabric8/zjsonpatch/0.3.0
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/io/fabric8/zjsonpatch/0.3.0/zjsonpatch-0.3.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/flipkart/zjsonpatch/zjsonpatch/0.4.4/zjsonpatch-0.4.4.jar
/usr/share/java/.m2/repository/com/flipkart/zjsonpatch/zjsonpatch/0.4.4/zjsonpatch-0.4.4.pom
/usr/share/java/.m2/repository/io/fabric8/zjsonpatch/0.3.0/zjsonpatch-0.3.0.jar
/usr/share/java/.m2/repository/io/fabric8/zjsonpatch/0.3.0/zjsonpatch-0.3.0.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-zjsonpatch/LICENSE
