#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-zjsonpatch
Version  : 0.3.0
Release  : 2
URL      : https://github.com/fabric8io/zjsonpatch/archive/v0.3.0.tar.gz
Source0  : https://github.com/fabric8io/zjsonpatch/archive/v0.3.0.tar.gz
Source1  : https://repo1.maven.org/maven2/io/fabric8/zjsonpatch/0.3.0/zjsonpatch-0.3.0.jar
Source2  : https://repo1.maven.org/maven2/io/fabric8/zjsonpatch/0.3.0/zjsonpatch-0.3.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-zjsonpatch-data = %{version}-%{release}

%description
# This is an implementation of  [RFC 6902 JSON Patch](http://tools.ietf.org/html/rfc6902) written in Java.

%package data
Summary: data components for the mvn-zjsonpatch package.
Group: Data

%description data
data components for the mvn-zjsonpatch package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/fabric8/zjsonpatch/0.3.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/io/fabric8/zjsonpatch/0.3.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/fabric8/zjsonpatch/0.3.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/io/fabric8/zjsonpatch/0.3.0


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/io/fabric8/zjsonpatch/0.3.0/zjsonpatch-0.3.0.jar
/usr/share/java/.m2/repository/io/fabric8/zjsonpatch/0.3.0/zjsonpatch-0.3.0.pom
